In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [3]:
from xverse.transformer import MonotonicBinning, WOE

In [4]:
df = pd.read_csv('df_EDA.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,G,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,G,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,G,S

In [5]:
df = df.drop(['Name','Ticket'],1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885 entries, 0 to 884
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  885 non-null    int64
 1   Survived     885 non-null    int64
 2   Pclass       885 non-null    int64
 3   Sex          885 non-null    object
 4   Age          885 non-null    int64
 5   SibSp        885 non-null    int64
 6   Parch        885 non-null    int64
 7   Fare         885 non-null    float64
 8   Cabin        885 non-null    object
 9   Embarked     885 non-null    object
dtypes: float64(1), int64(6), object(3)
memory usage: 69.3+ KB

In [7]:
y = df['Survived']
X = df.drop(['Survived', 'PassengerId'], 1)

In [8]:
print("Survived:", sum(y))
print("Total:", len(y))

Survived: 337
Total: 885

In [9]:
clf = MonotonicBinning()
clf.fit(X,y)

MonotonicBinning(force_bins=4)

In [10]:
print(clf.bins)

{'Pclass': array([1., 2., 3.]), 'Age': array([ 0., 24., 33., 80.]), 'SibSp': array([0., 1., 8.]), 'Parch': array([0., 1., 6.]), 'Fare': array([  0.        ,   8.65973333,  26.        , 263.        ])}

WOE

In [14]:
clf = WOE()
clf.fit(X,y)

WOE(mono_custom_binning={'Age': array([ 0., 24., 33., 80.]),
                         'Fare': array([  0.        ,   8.65973333,  26.        , 263.        ]),
                         'Parch': array([0., 1., 6.]),
                         'Pclass': array([1., 2., 3.]),
                         'SibSp': array([0., 1., 8.])},
    woe_bins={'Age': {Interval(-0.001, 24.0, closed='right'): 0.3469952264354537,
                      Interval(24.0, 33.0, closed='right'): -0.5327525293385846,
                      Interval(33.0, 80.0, closed='right'): 0.06555245046...
              'Parch': {Interval(-0.001, 1.0, closed='right'): -0.042225060483907485,
                        Interval(1.0, 6.0, closed='right'): 0.3385563577895893},
              'Pclass': {1: 0.9919418273297839, 2: 0.37738949674685457,
                         3: -0.6535780045659634},
              'Sex': {'female': 1.5298225108464105,
                      'male': -0.9873080666113372},
              'SibSp': {Interval(-0.001, 1.0, closed='right'): 0.04255861328501184,
                        Interval(1.0, 8.0, closed='right'): -0.5070594164146296}})

In [16]:
clf.woe_bins

{'Pclass': {1: 0.9919418273297839,
  2: 0.37738949674685457,
  3: -0.6535780045659634},
 'Sex': {'female': 1.5298225108464105, 'male': -0.9873080666113372},
 'Age': {Interval(-0.001, 24.0, closed='right'): 0.3469952264354537,
  Interval(24.0, 33.0, closed='right'): -0.5327525293385846,
  Interval(33.0, 80.0, closed='right'): 0.06555245046825432},
 'SibSp': {Interval(-0.001, 1.0, closed='right'): 0.04255861328501184,
  Interval(1.0, 8.0, closed='right'): -0.5070594164146296},
 'Parch': {Interval(-0.001, 1.0, closed='right'): -0.042225060483907485,
  Interval(1.0, 6.0, closed='right'): 0.3385563577895893},
 'Fare': {Interval(-0.001, 8.66, closed='right'): -0.8790485953264043,
  Interval(8.66, 26.0, closed='right'): 0.033430533784424385,
  Interval(26.0, 263.0, closed='right'): 0.7015537674678087},
 'Cabin': {'A': 0.35266096397113117,
  'B': 1.4352729112927998,
  'C': 0.6498217803774559,
  'D': 1.6256266397840187,
  'E': 1.6256266397840187,
  'F': 0.3162933198002563,
  'G': -0.6850775776485312},
 'Embarked': {'C': 0.6685139133896084,
  'Q': 0.037242136547750514,
  'S': -0.18834963613325698}}

In [17]:
clf.woe_bins

{'Pclass': {1: 0.9919418273297839,
  2: 0.37738949674685457,
  3: -0.6535780045659634},
 'Sex': {'female': 1.5298225108464105, 'male': -0.9873080666113372},
 'Age': {Interval(-0.001, 24.0, closed='right'): 0.3469952264354537,
  Interval(24.0, 33.0, closed='right'): -0.5327525293385846,
  Interval(33.0, 80.0, closed='right'): 0.06555245046825432},
 'SibSp': {Interval(-0.001, 1.0, closed='right'): 0.04255861328501184,
  Interval(1.0, 8.0, closed='right'): -0.5070594164146296},
 'Parch': {Interval(-0.001, 1.0, closed='right'): -0.042225060483907485,
  Interval(1.0, 6.0, closed='right'): 0.3385563577895893},
 'Fare': {Interval(-0.001, 8.66, closed='right'): -0.8790485953264043,
  Interval(8.66, 26.0, closed='right'): 0.033430533784424385,
  Interval(26.0, 263.0, closed='right'): 0.7015537674678087},
 'Cabin': {'A': 0.35266096397113117,
  'B': 1.4352729112927998,
  'C': 0.6498217803774559,
  'D': 1.6256266397840187,
  'E': 1.6256266397840187,
  'F': 0.3162933198002563,
  'G': -0.6850775776485312},
 'Embarked': {'C': 0.6685139133896084,
  'Q': 0.037242136547750514,
  'S': -0.18834963613325698}}

In [18]:
clf.mono_custom_binning

{'Pclass': array([1., 2., 3.]),
 'Age': array([ 0., 24., 33., 80.]),
 'SibSp': array([0., 1., 8.]),
 'Parch': array([0., 1., 6.]),
 'Fare': array([  0.        ,   8.65973333,  26.        , 263.        ])}

In [21]:
df_woe = clf.woe_df
df_woe

,Variable_Name,Category,Count,Event,Non_Event,Event_Rate,Non_Event_Rate,Event_Distribution,Non_Event_Distribution,WOE,Information_Value
0,Pclass,1,210,131,79,0.623810,0.376190,0.388724,0.144161,0.991942,0.486100
1,Pclass,2,184,87,97,0.472826,0.527174,0.258160,0.177007,0.377389,0.486100
2,Pclass,3,491,119,372,0.242363,0.757637,0.353116,0.678832,-0.653578,0.486100
3,Sex,female,311,230,81,0.739550,0.260450,0.682493,0.147810,1.529823,1.345865
4,Sex,male,574,107,467,0.186411,0.813589,0.317507,0.852190,-0.987308,1.345865
5,Age,"(-0.001, 24.0]",331,154,177,0.465257,0.534743,0.456973,0.322993,0.346995,0.130148
6,Age,"(24.0, 33.0]",279,74,205,0.265233,0.734767,0.219585,0.374088,-0.532753,0.130148
7,Age,"(33.0, 80.0]",275,109,166,0.396364,0.603636,0.323442,0.302920,0.065552,0.130148
8,SibSp,"(-0.001, 1.0]",811,317,494,0.390875,0.609125,0.940653,0.901460,0.042559,0.021541
9,SibSp,"(1.0, 8.0]",74,20,54,0.270270,0.729730,0.059347,0.098540,-0.507059,0.021541
10,Parch,"(-0.001, 1.0]",790,293,497,0.370886,0.629114,0.869436,0.906934,-0.042225,0.014279
11,Parch,"(1.0, 6.0]",95,44,51,0.463158,0.536842,0.130564,0.093066,0.338556,0.014279
12,Fare,"(-0.001, 8.66]",295,60,235,0.203390,0.796610,0.178042,0.428832,-0.879049,0.388774
13,Fare,"(8.66, 26.0]",301,117,184,0.388704,0.611296,0.347181,0.335766,0.033431,0.388774
14,Fare,"(26.0, 263.0]",289,160,129,0.553633,0.446367,0.474777,0.235401,0.701554,0.388774
15,Cabin,A,15,7,8,0.466667,0.533333,0.020772,0.014599,0.352661,0.595976
16,Cabin,B,43,31,12,0.720930,0.279070,0.091988,0.021898,1.435273,0.595976
17,Cabin,C,98,53,45,0.540816,0.459184,0.157270,0.082117,0.649822,0.595976
18,Cabin,D,33,25,8,0.757576,0.242424,0.074184,0.014599,1.625627,0.595976
19,Cabin,E,33,25,8,0.757576,0.242424,0.074184,0.014599,1.625627,0.595976
20,Cabin,F,177,81,96,0.457627,0.542373,0.240356,0.175182,0.316293,0.595976
21,Cabin,G,486,115,371,0.236626,0.763374,0.341246,0.677007,-0.685078,0.595976
22,Embarked,C,165,90,75,0.545455,0.454545,0.267062,0.136861,0.668514,0.112299
23,Embarked,Q,77,30,47,0.389610,0.610390,0.089021,0.085766,0.037242,0.112299
24,Embarked,S,643,217,426,0.337481,0.662519,0.643917,0.777372,-0.188350,0.112299

In [26]:
# # Cabin IV > 0.5, so checking the feature
# sns.countplot(x=df['Cabin'], hue=y)
# plt.show()

In [28]:
df_woe_imp = df_woe[df_woe['Information_Value'].between(0.1,0.6)]
df_woe_imp

,Variable_Name,Category,Count,Event,Non_Event,Event_Rate,Non_Event_Rate,Event_Distribution,Non_Event_Distribution,WOE,Information_Value
0,Pclass,1,210,131,79,0.623810,0.376190,0.388724,0.144161,0.991942,0.486100
1,Pclass,2,184,87,97,0.472826,0.527174,0.258160,0.177007,0.377389,0.486100
2,Pclass,3,491,119,372,0.242363,0.757637,0.353116,0.678832,-0.653578,0.486100
5,Age,"(-0.001, 24.0]",331,154,177,0.465257,0.534743,0.456973,0.322993,0.346995,0.130148
6,Age,"(24.0, 33.0]",279,74,205,0.265233,0.734767,0.219585,0.374088,-0.532753,0.130148
7,Age,"(33.0, 80.0]",275,109,166,0.396364,0.603636,0.323442,0.302920,0.065552,0.130148
12,Fare,"(-0.001, 8.66]",295,60,235,0.203390,0.796610,0.178042,0.428832,-0.879049,0.388774
13,Fare,"(8.66, 26.0]",301,117,184,0.388704,0.611296,0.347181,0.335766,0.033431,0.388774
14,Fare,"(26.0, 263.0]",289,160,129,0.553633,0.446367,0.474777,0.235401,0.701554,0.388774
15,Cabin,A,15,7,8,0.466667,0.533333,0.020772,0.014599,0.352661,0.595976
16,Cabin,B,43,31,12,0.720930,0.279070,0.091988,0.021898,1.435273,0.595976
17,Cabin,C,98,53,45,0.540816,0.459184,0.157270,0.082117,0.649822,0.595976
18,Cabin,D,33,25,8,0.757576,0.242424,0.074184,0.014599,1.625627,0.595976
19,Cabin,E,33,25,8,0.757576,0.242424,0.074184,0.014599,1.625627,0.595976
20,Cabin,F,177,81,96,0.457627,0.542373,0.240356,0.175182,0.316293,0.595976
21,Cabin,G,486,115,371,0.236626,0.763374,0.341246,0.677007,-0.685078,0.595976
22,Embarked,C,165,90,75,0.545455,0.454545,0.267062,0.136861,0.668514,0.112299
23,Embarked,Q,77,30,47,0.389610,0.610390,0.089021,0.085766,0.037242,0.112299
24,Embarked,S,643,217,426,0.337481,0.662519,0.643917,0.777372,-0.188350,0.112299

In [29]:
X2 = clf.transform(X[df_woe['Variable_Name'].unique()])
X2

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,-0.653578,-0.987308,0.346995,0.042559,-0.042225,-0.879049,-0.685078,-0.188350
1,0.991942,1.529823,0.065552,0.042559,-0.042225,0.701554,0.649822,0.668514
2,-0.653578,1.529823,-0.532753,0.042559,-0.042225,-0.879049,-0.685078,-0.188350
3,0.991942,1.529823,0.065552,0.042559,-0.042225,0.701554,0.649822,-0.188350
4,-0.653578,-0.987308,0.065552,0.042559,-0.042225,-0.879049,-0.685078,-0.188350
...,...,...,...,...,...,...,...,...
880,0.377389,-0.987308,-0.532753,0.042559,-0.042225,0.033431,0.316293,-0.188350
881,0.991942,1.529823,0.346995,0.042559,-0.042225,0.701554,1.435273,-0.188350
882,-0.653578,1.529823,0.346995,0.042559,0.338556,0.033431,-0.685078,-0.188350
883,0.991942,-0.987308,-0.532753,0.042559,-0.042225,0.701554,0.649822,0.668514
884,-0.653578,-0.987308,-0.532753,0.042559,-0.042225,-0.879049,-0.685078,0.037242

In [30]:
woe_data = pd.concat([X2, y], 1)
woe_data

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Survived
0,-0.653578,-0.987308,0.346995,0.042559,-0.042225,-0.879049,-0.685078,-0.188350,0
1,0.991942,1.529823,0.065552,0.042559,-0.042225,0.701554,0.649822,0.668514,1
2,-0.653578,1.529823,-0.532753,0.042559,-0.042225,-0.879049,-0.685078,-0.188350,1
3,0.991942,1.529823,0.065552,0.042559,-0.042225,0.701554,0.649822,-0.188350,1
4,-0.653578,-0.987308,0.065552,0.042559,-0.042225,-0.879049,-0.685078,-0.188350,0
...,...,...,...,...,...,...,...,...,...
880,0.377389,-0.987308,-0.532753,0.042559,-0.042225,0.033431,0.316293,-0.188350,0
881,0.991942,1.529823,0.346995,0.042559,-0.042225,0.701554,1.435273,-0.188350,1
882,-0.653578,1.529823,0.346995,0.042559,0.338556,0.033431,-0.685078,-0.188350,0
883,0.991942,-0.987308,-0.532753,0.042559,-0.042225,0.701554,0.649822,0.668514,1
884,-0.653578,-0.987308,-0.532753,0.042559,-0.042225,-0.879049,-0.685078,0.037242,0

In [31]:
woe_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885 entries, 0 to 884
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    885 non-null    float64
 1   Sex       885 non-null    float64
 2   Age       885 non-null    float64
 3   SibSp     885 non-null    float64
 4   Parch     885 non-null    float64
 5   Fare      885 non-null    float64
 6   Cabin     885 non-null    float64
 7   Embarked  885 non-null    float64
 8   Survived  885 non-null    int64
dtypes: float64(8), int64(1)
memory usage: 62.4 KB

In [32]:
woe_data.to_csv('df_WOE.csv', index=False)